services:
    dmzx.topicauthor.admin.controller:
        class: dmzx\topicauthor\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@request'
    dmzx.topicauthor.listener:
        class: dmzx\topicauthor\event\listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }
